
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: tendersys.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      # - Hostname: orderer2
      #   SANS:
      #     - "localhost"
      #     - "127.0.0.1"
      # - Hostname: orderer3
      #   SANS:
      #       - "localhost"
      #       - "127.0.0.1"

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Bidder
    Domain: bidder.tendersys.com
    EnableNodeOUs: true

    Template:
      Count: 2
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Gov
    Domain: gov.tendersys.com
    EnableNodeOUs: true

    Template:
      Count: 4
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Bank
    Domain: bank.tendersys.com
    EnableNodeOUs: true

    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
      SANS:
        - "localhost"

    Users:
      Count: 1