---
name: first-network-org2
version: 1.0.0
client:
  organization: Gov
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Gov:
    mspid: GovMSP
    peers:
    - peer0.gov.tendersys.com
    - peer1.gov.tendersys.com
    certificateAuthorities:
    - ca.gov.tendersys.com
peers:
  peer0.gov.tendersys.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWzCCAgKgAwIBAgIRAJtqPOLbGvPF4qK6AAmJ1NYwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEWdvdi50ZW5kZXJzeXMuY29tMSAwHgYDVQQDExd0
        bHNjYS5nb3YudGVuZGVyc3lzLmNvbTAeFw0yMDA3MTcwOTU2MDBaFw0zMDA3MTUw
        OTU2MDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFnb3YudGVuZGVyc3lzLmNvbTEg
        MB4GA1UEAxMXdGxzY2EuZ292LnRlbmRlcnN5cy5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAATG6NRB9CR7QisX03E6fW89eA1mNZEcPZSHOMfFcZZjv7Daf0Mv
        gzaUT91anM/zxdi8gJ0Wv7aKb0NGIkLDzh49o20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIHRYmcL0zKbYyEmFt6f1z6UyZY1tTsdRAW7H6nekL05/MAoGCCqG
        SM49BAMCA0cAMEQCIBBOu7QQTROVk+Qq5qIQauLsld901LqAT7FwTLrQ1sXSAiBa
        KRp4zmmKj8z4yB3baIRjKZRH7mLWaKivZz0EL9EnyA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.gov.tendersys.com
      hostnameOverride: peer0.gov.tendersys.com
  peer1.gov.tendersys.com:
    url: grpcs://localhost:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf2gAwIBAgIQU4hPthwz91ncEHRSu0EwpjAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yMDA0MTIwNDA1MDBaFw0zMDA0MTAwNDA1
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAExoqdrP4xlblRMdCppih7vIwsUl+Rmkenva8XaMphn4VglgTtbDd0gRkG
        5k87TddnfbmSjWBfDmpK4weBNqI2caNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCB0EVyV6BUon9rvUYEAeeCDhqp5SeTTIdCOCARv9nMbljAKBggqhkjOPQQD
        AgNJADBGAiEAz1VJgBZLjEPXnIcA1P+OmgNgZvV00Kb+2H/uxqFJeWkCIQCW4IMS
        UopQ8oJrD5lYGwCmkRAY6OPFKBO5gN3ZjrqTZw==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.gov.tendersys.com
      hostnameOverride: peer1.gov.tendersys.com
certificateAuthorities:
  ca.gov.tendersys.com:
    url: https://localhost:8054
    caName: ca-gov
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWzCCAgKgAwIBAgIRAJtqPOLbGvPF4qK6AAmJ1NYwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEWdvdi50ZW5kZXJzeXMuY29tMSAwHgYDVQQDExd0
        bHNjYS5nb3YudGVuZGVyc3lzLmNvbTAeFw0yMDA3MTcwOTU2MDBaFw0zMDA3MTUw
        OTU2MDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFnb3YudGVuZGVyc3lzLmNvbTEg
        MB4GA1UEAxMXdGxzY2EuZ292LnRlbmRlcnN5cy5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAATG6NRB9CR7QisX03E6fW89eA1mNZEcPZSHOMfFcZZjv7Daf0Mv
        gzaUT91anM/zxdi8gJ0Wv7aKb0NGIkLDzh49o20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIHRYmcL0zKbYyEmFt6f1z6UyZY1tTsdRAW7H6nekL05/MAoGCCqG
        SM49BAMCA0cAMEQCIBBOu7QQTROVk+Qq5qIQauLsld901LqAT7FwTLrQ1sXSAiBa
        KRp4zmmKj8z4yB3baIRjKZRH7mLWaKivZz0EL9EnyA==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
